#services:
#  web:
#    build: ./app
#    volumes: 
#      - ${PWD}/django:/usr/src/app
#    ports:
#      - 8000:8000
#    networks:
#      - django-network
#    env_file:
#      - .env
#  nginx:
#    build: ./nginx
#    volumes:
#      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ${PWD}/nginx/robots.txt:/usr/src/app/robots.txt
#      - /etc/letsencrypt:/etc/letsencrypt
#      - ${PWD}/frontend/dist/:/usr/share/nginx/html
#    ports:
#      - 80:80
#      - 443:443
#    networks:
#      - django-network
#    depends_on:
#      - web
#  jenkins:
#    image: "jenkins/jenkins:lts-jdk17"
#    ports:
#      - 8080:8080
#      - 50000:50000
#    privileged: true
#    user: root
#    volumes:
#      - ${PWD}/jenkins/jenkins_data:/var/jenkins_home
#    networks:
#      - django-network
#networks:
#  django-network:
#    driver: bridge
