services:
  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - django-network
  web:
    build: ./web
    volumes: 
      - ./web:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - django-network
    env_file:
      - .env
    depends_on:
      - db
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - django-network

networks:
  django-network:
    driver: bridge
