services:
  web:
    build: 
      context: backend
      dockerfile: dev.Dockerfile
    volumes: 
      - ./backend:/app
    ports:
      - 8000:8000
    entrypoint: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - 5173:5173
    environment:
      - VITE_WS_URL=ws://localhost:80

  nginx:
    build:
      context: nginx
      dockerfile: dev.Dockerfile
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - web

networks:
  default:
    driver: bridge

volumes:
  uv-data:
