services:
  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - django-network
  web:
    build: ./web
    volumes: 
      - ${PWD}/web:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - django-network
    env_file:
      - .env
    depends_on:
      - db
  jenkins:
    image: "jenkins/jenkins:lts-jdk17"
    ports:
      - 8080:8080
      - 50000:50000
    privileged: true
    env_file:
      - .env
    user: root
    volumes:
      - ${PWD}/jenkins_data:/var/jenkins_home
    networks:
      - django-network
  nginx:
    build: ./nginx
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ${PWD}/web/robots.txt:/usr/src/app/robots.txt
    ports:
      - 80:80
      - 443:443
    networks:
      - django-network
    depends_on:
      - web
networks:
  django-network:
    driver: bridge
