apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: nginx
          image: ghcr.io/sunba23/sunbadev-nginx:prod
          env:
            - name: ENVIRONMENT
              value: "production"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
