apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-sunbadev
spec:
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: traefik
          args:
            - --api=true
            - --providers.kubernetesingress=true
            - --entrypoints.web.address=:8001
            - --entrypoints.websecure.address=:8443
            - --providers.kubernetesIngress.ingressClass=traefik-sunbadev-prod
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-sunbadev
spec:
  ports:
    - name: web
      port: 8001
    - name: websecure
      port: 8443
