apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: staging
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/sunba23/sunbadev-api:staging
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: "staging"
