apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    # want staging.sunba.dev to be available to public for user tests
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik-sunbadev-staging
  tls:
  - hosts:
    - staging.sunba.dev
    secretName: sunba-staging-tls
  rules:
  - host: staging.sunba.dev
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik-sunbadev-staging
