apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: staging
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: ghcr.io/sunba23/sunbadev-nginx:staging
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: "staging"
