apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: traefik
          args:
            - --providers.kubernetesingress.ingressclass=traefik
            - --providers.kubernetesingress.namespaces=default,staging
