apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
resources:
  - ../../base

patches:
  - path: patches/fastapi-resources.yaml
  - path: patches/nginx-resources.yaml
  - path: patches/ingress-resources.yaml
