- name: Download k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Install k3s
  command: /tmp/k3s-install.sh
  args:
    creates: /usr/local/bin/k3s

- name: Wait for k3s to be ready
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    state: present
    delay: 10
    timeout: 300

- name: Create .kube directory for deploy user
  file:
    path: /home/deploy/.kube
    state: directory
    owner: deploy
    group: deploy

- name: Copy k3s config for deploy user
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/deploy/.kube/config
    remote_src: yes
    owner: deploy
    group: deploy
