apiVersion: v1
kind: Service
metadata:
  name: traefik-sunbadev
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 8001
      protocol: TCP
    - name: websecure
      port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: traefik-sunbadev
