apiVersion: v1
kind: Service
metadata:
  name: traefik-sunbadev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8001
      protocol: TCP
      name: web
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: websecure
  selector:
    app: traefik-sunbadev
