apiVersion: v1
kind: Service
metadata:
  name: traefik-sunbadev
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 8001
      targetPort: web
    - name: websecure
      port: 8443
      targetPort: websecure
  selector:
    app: traefik-sunbadev
